### ISSUE TITLE
When calibrating, the trackers are straight up not moving how they should

### ISSUE THREAD

**Issue by Blixtdraken** [justinliang1020/AirPose#5]
This could be acompanied side effect of [this](https://github.com/justinliang1020/AirPose/issues/4) issue but when I try and use the program and calibrate it the trackers apear under me but when I move around the only thing that chnages about them is how high up or down they are, only way they move other directions is when I move my headset.

**Comment by JayVer107** [comment]
I think I maybe have some issue similar to this
for me they just float above me and don't really move much

**Comment by justinliang1020** [comment]
Closing issue as it's a similar problem to #4 . Still working to resolve referenced issue
